### ISSUE TITLE
[Drop][v1.1]Failed to install the app.

### ISSUE THREAD

**Issue by masudr4n4** [petermcneil/drop#1]
<h4>Actual Behaviour </h4>
App fail to install in my device.
<h4>Expected Behaviour </h4>
I expected that i can install and use the app successfully. 
<h4>Step to reproduce </h4>
<ol>
<li>Diwnload the app from release page</li>
<li>click the app to install</li>
<li>see the error</li>
</ol>
<h4>Information </h4>
<ul>
<li>App version:v1.1</li>
<li>Os:Android 9.0</li>
<li>Device:Samsung A10</li>
</ul>
<h4>Recording of the bug</h4>
<a href="https://youtu.be/8wm7vzLeKz0">https://youtu.be/8wm7vzLeKz0</a>

**Comment by petermcneil** [comment]
Hi :wave:

Thanks for reporting this. I pretty new to android development and have never had anyone else install it. 

This should be fixed now, can you try installing the v1.2.1 app?

Cheers!

**Comment by masudr4n4** [comment]
Tnx it installed now.

**Comment by masudr4n4** [comment]
Hi @petermcneil  again failed  to install  app in the last version  1.2.2.can you chack it again?
