### ISSUE TITLE
 [Drop][v1.2.5]Failed to install the app.

### ISSUE THREAD

**Issue by 44asad** [petermcneil/drop#11]
### Actual Behaviour

App fail to install in my device.
### Expected Behaviour

I expected that i can install and use the app successfully.
### How to Reproduce
* Download the app from release page
* click the app to install
* see the error
### Information
App version:v1.2.5
Os:Android 5.0.1
Device:Samsung j2
### Recording of the bug
https://youtu.be/hxRKCC9T7r8

**Comment by realrufans** [comment]
Worked perfectly with Android 8.
It didn't install on my Android 5.1

I guess it only supports Android 6, and later?

**Comment by 44asad** [comment]
ok sir thanks you

**Comment by petermcneil** [comment]
Yeah, sorry Drop only supports 6.0+. I will updated the README.md.
