### ISSUE TITLE
[Drop][v1.2.1]App unable to edit profile.

### ISSUE THREAD

**Issue by masudr4n4** [petermcneil/drop#2]
<h4>Actual behavior</h4>
I can not edit profile,I click edit profile,no action occuring.
<h4>Expected behavior</h4>
Expected that i can edit my profile from the app.
<h4>How to reproduce</h4>
<ol>
<li>Install the apps and open the app</li>
<li>Create account and login</li>
<li>Click setting icon and click Edit profile</li>
<li>See the error</li>
</ol>
<h4>Information</h4>
<ul>
<li>App version:V1.2.1</li>
<li>OS:Android 9.0</li>
<li>Device:Samsung A10</li>
</ul>
<h4>Recording Of The Bug</h4>
<a href="https://youtu.be/BtWBzpBXz1A">https://youtu.be/BtWBzpBXz1A</a>

**Comment by maaudrana** [comment]
@petermcneil can you pls add bug lebel if i did little help?
.

**Comment by petermcneil** [comment]
This feature is not yet implemented, I should remove the button - or have it display a snackbar
