### ISSUE TITLE
[Drop][v1.2.1]App failed to open.

### ISSUE THREAD

**Issue by masudr4n4** [petermcneil/drop#3]
<h4>Actual behavior</h4>
App continously crashing ,can not open the app.
<h4>Expected behavior</h4>
Expected that i can open the app and can use successfully
<h4>How to reproduce</h4>
<ol>
<li>Install the apps and open the app</li>
<li>Use app some times</li>
<li>Minmize the app and clear the app from recent used app.</li>
<li>Now try to open the app again.</li>
<li>If you able to open the app then use the app sometime again.</li>
<li>Do 2-4 steps again.</li>
<li>See the error</li>
</ol>
<h4>Information</h4>
<ul>
<li>App version:v1.2.1</li>
<li>OS:Android 9.0</li>
<li>Device:Samsung A10</li>
</ul>
<h4>Recording Of The Bug</h4>
<a href="https://youtu.be/l883rDY7nGU">https://youtu.be/l883rDY7nGU</a>
<h4>Logcat</h4>
<pre>
<code>
05-05 13:24:53.927 19979 19979 E AndroidRuntime: FATAL EXCEPTION: main
05-05 13:24:53.927 19979 19979 E AndroidRuntime: Process: mcneil.peter.drop, PID: 19979
05-05 13:24:53.927 19979 19979 E AndroidRuntime: d.f: lateinit property firebaseUtil has not been initialized
05-05 13:24:53.927 19979 19979 E AndroidRuntime: 	at mcneil.peter.drop.DropApp$a.c(Unknown Source:9)
05-05 13:24:53.927 19979 19979 E AndroidRuntime: 	at mcneil.peter.drop.b.e.Q(Unknown Source:12)
05-05 13:24:53.927 19979 19979 E AndroidRuntime: 	at b.j.a.h.Z(Unknown Source:18)
05-05 13:24:53.927 19979 19979 E AndroidRuntime: 	at b.j.a.u.a(Unknown Source:684)
05-05 13:24:53.927 19979 19979 E AndroidRuntime: 	at b.j.a.u.h(Unknown Source:38)
05-05 13:24:53.927 19979 19979 E AndroidRuntime: 	at b.j.a.u.a(Unknown Source:46)
05-05 13:24:53.927 19979 19979 E AndroidRuntime: 	at b.j.a.u.e(Unknown Source:4)
05-05 13:24:53.927 19979 19979 E AndroidRuntime: 	at b.j.a.u.l(Unknown Source:6)
05-05 13:24:53.927 19979 19979 E AndroidRuntime: 	at b.j.a.l.g(Unknown Source:4)
05-05 13:24:53.927 19979 19979 E AndroidRuntime: 	at b.j.a.j.onStart(Unknown Source:30)
05-05 13:24:53.927 19979 19979 E AndroidRuntime: 	at androidx.appcompat.app.m.onStart(Unknown Source:0)
05-05 13:24:53.927 19979 19979 E AndroidRuntime: 	at mcneil.peter.drop.activities.MainActivity.onStart(Unknown Source:0)
05-05 13:24:53.927 19979 19979 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1395)
05-05 13:24:53.927 19979 19979 E AndroidRuntime: 	at android.app.Activity.performStart(Activity.java:7348)
05-05 13:24:53.927 19979 19979 E AndroidRuntime: 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3139)
05-05 13:24:53.927 19979 19979 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
05-05 13:24:53.927 19979 19979 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
05-05 13:24:53.927 19979 19979 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
05-05 13:24:53.927 19979 19979 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
05-05 13:24:53.927 19979 19979 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955)
05-05 13:24:53.927 19979 19979 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-05 13:24:53.927 19979 19979 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
05-05 13:24:53.927 19979 19979 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7073)
05-05 13:24:53.927 19979 19979 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-05 13:24:53.927 19979 19979 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
05-05 13:24:53.927 19979 19979 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
</code>
</pre>

**Comment by petermcneil** [comment]
Oo, I thought I had fixed all the errors to do with firebaseUtil. Thank you for the stacktrace, that will be helpful!
