### ISSUE TITLE
Bug: App get stuck on mian page, even after login out, and I can't sign in again

### ISSUE THREAD

**Issue by darewealth** [petermcneil/drop#4]
### Describe the bug.

When I signed into the app, the app welcome and displays my name, but when I click on sign out, it does not take me to the main page. It signs out but remains on the sign in page, and I get stuck and won't be able to sign in again.

### Steps to reproduce.

* Launch the app

* Log in

* Click on setting and log out

### Expected Behaviour

I expect that I should be able to sign out and sign in freely.

### Screen recording
https://youtu.be/Yy2Sh92G5Tc

### Devices and Versions)

* Device: [itel]

* Version [6.1]

* App version [1.2.2]

**Comment by petermcneil** [comment]
Hi! 👋 

Thank you for reporting this 😄 I found the issue.

When signing out the app forgets to set a preference which indicates whether it is logged in or not. Adding that in and another check in the updateUI method means that when a person logs out, they are correctly shown the LoginActivity.

Cheers!

**Comment by petermcneil** [comment]
Fixed in v1.2.3
