### ISSUE TITLE
Bug: App can't authenticate correct password, and I can't sign in again

### ISSUE THREAD

**Issue by jubreal** [petermcneil/drop#5]
#### Expected Behaviour
I expect that I should be able to sign in with after my correct login details have been provided after signing out.

#### Describe the bug.
When I signed into the app with my correct login details, the app welcome and displays my name, so I signed out. I tried signing in again, but when I inputted my correct login details and click on log in, the app fails to recognize the password and returns with the message "wrong password" even though the password is correct. And I couldn't sign in again.

#### Steps to reproduce.
- Launch the app

- Log in

- Click on setting and log out

- Insert your correct login credentials (email and password) again and click on login.
You'll see the bug

##### Screen recording
https://youtu.be/sMatbmOwofE

Devices and Versions)
Device: Infinix Note 3
Android Version 6.0

App version 1.2.3

**Comment by petermcneil** [comment]
Hi 👋 

Thank you for reporting this and supplying a video! I suspect this is slightly linked to your other issue #6. 

This will be an easy enough fix - I will add in a reset password form and better feedback to the user about the reason for log in failure.

Cheers!

**Comment by jubreal** [comment]
Thanks for the timely response, yes it is linked to the issue https://github.com/petermcneil/drop/issues/6. I can see this app is in steady development and would like to provide help in any way I can to attain the ideal goal.
