### ISSUE TITLE
Suggestion To Improve Drop : Add "Forget Password" Option

### ISSUE THREAD

**Issue by jubreal** [petermcneil/drop#6]
#### Introduction

Drop according to the [developer description](https://github.com/petermcneil/drop/blob/master/README.md) will be an app where you can write a quick note or message and "drop it". When someone else with the app goes within 10m from where you dropped your message, they will pick-up your message.

Drop aims to aid the cause to spend more time outdoors, giving users a reason to head out and explore by providing a platform to share content about highly localized areas. Drop achieves this by giving users options to “drop” a message in the world and other users can find these drops by exploring outdoors, incentivizing exploration. 

#### Components
After downloading the app and in the course of my exploration of the app, I found out some a very important feature which is currently missing in the app which if not implemented could limit the use of the app and render it obsolete. So, I'm suggesting the "Forget Password" Option be included.

#### Proposal Description
Drop as I mentioned earlier will be an app where you can write a quick note or message and "drop it" for the people within 10M of the drop location will be able to access such message or note. It is an application that requires user signing in and therefore requires users to create their account before they can use it. We know sometimes users tend to forget details used in creating an account and so wouldn't be able to log in to their accounts. It is very important that they are provided with an option to regain their log in details either by sending them a reset link to the email provided during registration or by sending the password to the email provided during registration. 

#### Mockups / Examples
Below are pictorial illustrations of how the features I recommend can be implemented by the Developer.

This is how the app currently looks like without the feature![Screenshot_20190506104737.png](https://files.steempeak.com/file/steempeak/jubreal/lztwQJlF-Screenshot_20190506-104737.png)

This is a picture showing how the feature can be implemented
![PicsArt_050611.28.02.png](https://files.steempeak.com/file/steempeak/jubreal/7wFI2Pny-PicsArt_05-06-11.28.02.png)

#### Benefits
The benefits of the features suggested above are as follows:
- It will enable users to easily gain access to their account when they forget their passwords instead of going through the stress of creating another account.
- This will also save the database and the app server from having so many dormant and neglected accounts due to users forgetting their passwords.

#### Conclusion
Implementing the aforementioned feature may demand the developers would have to make major adjustments to the Drop app. But this is really needed as it will on the long run benefit both the developers and the users as you can see in the benefits mentioned above.

I hope, App developer implements this feature very soon.

Thank You.

**Comment by petermcneil** [comment]
Fixed in https://github.com/petermcneil/drop/commit/d1e84701c8ef03aa002da68b2d4a723c77ba100b
