### ISSUE TITLE
App v1.2.4 fails to install

### ISSUE THREAD

**Issue by jubreal** [petermcneil/drop#7]
#### Expected Behaviour
I expect that I should be able to install the newest version (1.2.4) of the app after download.

#### Describe the bug.
After downloading the drop version1.2.4, The app failed to install on my device

#### Steps to reproduce.
- Download the latest release from the github release page

- Install the app after completing download (Ensure you have uninstalled any other version of the app from your device in case there was any)

You'll see the bug

#### Screen recording
https://youtu.be/JWVBOc15OoY

Devices and Versions)
Device: Infinix Note 3
Android Version 6.0

App version 1.2.4

**Comment by petermcneil** [comment]
Hi! 👋 

Thank you for reporting this bug! 

I am aware of this and have been trying to find a solution. It occurs when a user uninstalls the app and tries to reinstall any version of the app.

A temporary fix is to restart your phone and reinstall it.

Cheers!

**Comment by jubreal** [comment]
I actually restarted my phone and tried to reinstall it, but I was only able to install the version 1.2.3 , the 1.2.4 still failed
